from nltk.corpus import wordnet
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('wordnet')


def get_synonyms(word):
    synonyms = set()
    for synset in wordnet.synsets(word):
        for lemma in synset.lemmas():
            synonyms.add(lemma.name())
    return synonyms


words = [
    "osteomalacia",
    "scoliosis",
    "fibrosis",
    "hypertension",
    "hypotension",
    "hyperlipidemia",
    "hypoglycemia",
    "hyperglycemia",
    "hemochromatosis",
    "anemia",
    "leukopenia",
    "thrombocytopenia",
    "hemophilia",
    "sickle cell disease",
    "thalassemia",
    "hemolytic anemia",
    "aplastic anemia",
    "pernicious anemia",
    "idiopathic thrombocytopenic purpura (ITP)",
    "von Willebrand disease",
    "polycythemia vera",
    "lymphedema",
    "lymphoma",
    "Hodgkin's lymphoma",
    "non-Hodgkin's lymphoma",
    "leukemia",
    "acute lymphoblastic leukemia (ALL)",
    "chronic lymphocytic leukemia (CLL)",
    "acute myeloid leukemia (AML)",
    "chronic myeloid leukemia (CML)",
    "myeloma",
    "thalassemia",
    "chronic fatigue syndrome",
    "fibromyalgia",
    "restless legs syndrome",
    "narcolepsy",
    "sleep apnea",
    "insomnia",
    "anorexia nervosa",
    "bulimia nervosa",
    "binge eating disorder",
    "obsessive-compulsive disorder (OCD)",
    "post-traumatic stress disorder (PTSD)",
    "social anxiety disorder",
    "panic disorder",
    "generalized anxiety disorder",
    "borderline personality disorder",
    "antisocial personality disorder",
    "schizoaffective disorder",
    "dissociative identity disorder",
    "attention deficit hyperactivity disorder (ADHD)",
    "oppositional defiant disorder (ODD)",
    "conduct disorder",
    "autism spectrum disorder",
    "intellectual disability",
    "obsessive-compulsive disorder (OCD)",
    "anxiety disorder",
    "mood disorder",
    "personality disorder",
    "psychotic disorder",
    "eating disorder",
    "substance use disorder",
    "depressive disorder",
    "schizophrenia",
    "borderline personality disorder",
    "bipolar disorder",
    "major depressive disorder",
    "postpartum depression",
    "seasonal affective disorder (SAD)",
    "dysthymia",
    "persistent depressive disorder",
    "adjustment disorder",
    "psychosis",
    "delusional disorder",
    "schizotypal personality disorder",
    "catatonic schizophrenia",
    "paranoid schizophrenia",
    "disorganized schizophrenia",
    "undifferentiated schizophrenia",
    "respiratory syncytial virus (RSV)",
    "influenza",
    "common cold",
    "pneumonia",
    "bronchitis",
    "sinusitis",
    "tuberculosis",
    "strep throat",
    "tonsillitis",
    "pharyngitis",
    "laryngitis",
    "otitis media",
    "conjunctivitis",
    "gastroenteritis",
    "gastritis",
    "gastroesophageal reflux disease (GERD)",
    "peptic ulcer disease",
    "irritable bowel syndrome (IBS)",
    "Crohn's disease",
    "ulcerative colitis",
    "diverticulosis",
    "diverticulitis",
    "gallstones",
    "hepatitis",
    "cirrhosis",
    "pancreatitis",
    "jaundice",
    "appendicitis",
    "kidney stones",
    "urinary tract infection (UTI)",
    "glomerulonephritis",
    "nephrotic syndrome",
    "acute kidney injury",
    "chronic kidney disease",
    "urinary incontinence",
    "benign prostatic hyperplasia (BPH)",
    "endometriosis",
    "polycystic ovary syndrome (PCOS)",
    "ovarian cysts",
    "menopause",
    "ectopic pregnancy",
    "infertility",
    "premenstrual syndrome (PMS)",
    "endometrial cancer",
    "ovarian cancer",
    "cervical cancer",
    "uterine cancer",
    "vaginal cancer",
    "breast cancer",
    "testicular cancer",
    "prostate cancer",
    "colon cancer",
    "rectal cancer",
    "bladder cancer",
    "kidney cancer",
    "liver cancer",
    "lung cancer",
    "esophageal cancer",
    "stomach cancer",
    "pancreatic cancer",
    "ovarian cancer",
    "cervical cancer",
    "endometrial cancer",
    "prostate cancer",
    "testicular cancer",
    "breast cancer",
    "lung cancer",
    "colorectal cancer",
    "pancreatic cancer",
    "liver cancer",
    "kidney cancer",
    "bladder cancer",
    "ovarian cancer",
    "cervical cancer",
    "leukemia",
    "lymphoma",
    "melanoma",
    "glioblastoma",
    "osteosarcoma",
    "sarcoma",
    "fibroids",
    "endometriosis",
    "ovarian cysts",
    "amenorrhea",
    "dysmenorrhea",
    "polycystic ovary syndrome (PCOS)",
    "premenstrual syndrome (PMS)",
    "menopause",
    "andropause",
    "erectile dysfunction",
    "prostate enlargement",
    "prostate cancer",
    "cryptorchidism",
    "varicocele",
    "testicular torsion",
    "epididymitis",
    "orchitis",
    "infertility",
    "endocrine disorders",
    "hypothyroidism",
    "hyperthyroidism",
    "diabetes",
    "hypoglycemia",
    "hyperglycemia",
    "adrenal insufficiency",
    "Cushing's syndrome",
    "Addison's disease",
    "acromegaly",
    "gigantism",
    "pituitary tumors",
    "parathyroid disorders",
    "osteoporosis",
    "hyperparathyroidism",
    "hypoparathyroidism",
    "sexually transmitted infections (STIs)",
    "chlamydia",
    "gonorrhea",
    "syphilis",
    "genital herpes",
    "human papillomavirus (HPV) infection",
    "trichomoniasis",
    "hepatitis B",
    "hepatitis C",
    "HIV/AIDS",
    "genital warts",
    "pelvic inflammatory disease (PID)",
    "prostatitis",
    "epididymitis",
    "orchitis",
    "scabies",
    "lice",
    "pinworms",
    "molluscum contagiosum",
    "scabies",
    "bedbugs",
    "ringworm",
    "athlete's foot",
    "fungal nail infections",
    "yeast infections",
    "thrush",
    "candidiasis",
    "tinea versicolor",
    "eczema",
    "psoriasis",
    "acne",
    "rosacea",
    "hives",
    "contact dermatitis",
    "cellulitis",
    "impetigo",
    "fifth disease",
    "shingles",
    "warts",
    "mumps",
    "measles",
    "rubella",
    "chickenpox",
    "hepatitis A",
    "hepatitis B",
    "hepatitis C",
    "hepatitis D",
    "hepatitis E",
    "influenza",
    "common cold",
    "pneumonia",
    "bronchitis",
    "sinusitis",
    "tuberculosis",
    "strep throat",
    "tonsillitis",
    "pharyngitis",
    "laryngitis",
    "otitis media",
    "conjunctivitis",
    "gastroenteritis",
    "gastritis",
    "gastroesophageal reflux disease (GERD)",
    "peptic ulcer disease",
    "irritable bowel syndrome (IBS)",
    "Crohn's disease",
    "ulcerative colitis",
    "diverticulosis",
    "diverticulitis",
    "gallstones",
    "kidney stones",
    "urinary tract infection (UTI)",
    "glomerulonephritis",
    "nephrotic syndrome",
    "acute kidney injury",
    "chronic kidney disease",
    "urinary incontinence",
    "endometriosis",
    "polycystic ovary syndrome (PCOS)",
    "ovarian cysts",
    "menopause",
    "ectopic pregnancy",
    "infertility",
    "premenstrual syndrome (PMS)",
    "endometrial cancer",
    "ovarian cancer",
    "cervical cancer",
    "uterine cancer",
    "vaginal cancer",
    "breast cancer",
    "testicular cancer",
    "prostate cancer",
    "colon cancer",
    "rectal cancer",
    "bladder cancer",
    "kidney cancer",
    "liver cancer",
    "lung cancer",
    "esophageal cancer",
    "stomach cancer",
    "pancreatic cancer",
    "ovarian cancer",
    "cervical cancer",
    "endometrial cancer",
    "prostate cancer",
    "testicular cancer",
    "breast cancer",
    "lung cancer",
    "colorectal cancer",
    "pancreatic cancer",
    "liver cancer",
    "kidney cancer",
    "bladder cancer",
    "ovarian cancer",
    "cervical cancer",
    "leukemia",
    "lymphoma",
    "melanoma",
    "glioblastoma",
    "osteosarcoma",
    "sarcoma",
    "fibroids",
    "endometriosis",
    "ovarian cysts",
    "amenorrhea",
    "dysmenorrhea",
    "polycystic ovary syndrome (PCOS)",
    "premenstrual syndrome (PMS)",
    "menopause",
    "andropause",
    "erectile dysfunction",
    "prostate enlargement",
    "prostate cancer",
    "cryptorchidism",
    "varicocele",
    "testicular torsion",
    "epididymitis",
    "orchitis",
    "infertility",
    "hypothyroidism",
    "hyperthyroidism",
    "diabetes",
    "hypoglycemia",
    "hyperglycemia",
    "adrenal insufficiency",
    "Cushing's syndrome",
    "Addison's disease",
    "acromegaly",
    "pituitary tumors",
    "osteoporosis",
    "sexually transmitted infections (STIs)",
    "chlamydia",
    "gonorrhea",
    "syphilis",
    "genital herpes",
    "human papillomavirus (HPV) infection",
    "trichomoniasis",
    "hepatitis B",
    "hepatitis C",
    "HIV/AIDS",
    "genital warts",
    "pelvic inflammatory disease (PID)",
    "prostatitis",
    "epididymitis",
    "orchitis",
    "scabies",
    "lice",
    "pinworms",
    "molluscum contagiosum",
    "scabies",
    "bedbugs",
    "ringworm",
    "athlete's foot",
    "fungal nail infections",
    "yeast infections",
    "thrush",
    "candidiasis",
    "tinea versicolor",
    "eczema",
    "psoriasis",
    "acne",
    "rosacea",
    "hives",
    "contact dermatitis",
    "cellulitis",
    "impetigo",
    "fifth disease",
    "shingles",
    "warts",
    "mumps",
    "measles",
    "rubella",
    "chickenpox",
    "hepatitis A",
    "hepatitis B",
    "hepatitis C",
    "hepatitis D",
    "hepatitis E",
    "influenza",
    "common cold",
    "pneumonia",
    "bronchitis",
    "sinusitis",
    "tuberculosis",
    "strep throat",
    "tonsillitis",
    "pharyngitis",
    "laryngitis",
    "otitis media",
    "conjunctivitis",
    "gastroenteritis",
    "gastritis",
    "gastroesophageal reflux disease (GERD)",
    "peptic ulcer disease",
    "irritable bowel syndrome (IBS)",
    "Crohn's disease",
    "ulcerative colitis",
    "diverticulosis",
    "diverticulitis",
    "gallstones",
    "kidney stones",
    "urinary tract infection (UTI)",
    "glomerulonephritis",
    "nephrotic syndrome",
    "acute kidney injury",
    "chronic kidney disease",
    "urinary incontinence",
    "endometriosis",
    "polycystic ovary syndrome (PCOS)",
    "ovarian cysts",
    "menopause",
    "ectopic pregnancy",
    "infertility",
    "premenstrual syndrome (PMS)",
    "endometrial cancer",
    "ovarian cancer",
    "cervical cancer",
    "uterine cancer",
    "vaginal cancer",
    "breast cancer",
    "testicular cancer",
    "prostate cancer",
    "colon cancer",
    "rectal cancer",
    "bladder cancer",
    "kidney cancer",
    "liver cancer",
    "lung cancer",
    "esophageal cancer",
    "stomach cancer",
    "pancreatic cancer",
    "ovarian cancer",
    "cervical cancer",
    "endometrial cancer",
    "prostate cancer",
    "testicular cancer",
    "breast cancer",
    "lung cancer",
    "colorectal cancer",
    "pancreatic cancer",
    "liver cancer",
    "kidney cancer",
    "bladder cancer",
    "ovarian cancer",
    "cervical cancer",
    "leukemia",
    "lymphoma",
    "melanoma",
    "glioblastoma",
    "osteosarcoma",
    "sarcoma",
    "fibroids",
    "endometriosis",
    "ovarian cysts",
    "amenorrhea",
    "dysmenorrhea",
    "polycystic ovary syndrome (PCOS)",
    "premenstrual syndrome (PMS)",
    "menopause",
    "andropause",
    "erectile dysfunction",
    "prostate enlargement",
    "prostate cancer",
    "cryptorchidism",
    "varicocele",
    "testicular torsion",
    "epididymitis",
    "orchitis",
    "infertility",
    "hypothyroidism",
    "hyperthyroidism",
    "diabetes",
    "hypoglycemia",
    "hyperglycemia",
    "adrenal insufficiency",
    "Cushing's syndrome",
    "Addison's disease",
    "acromegaly",
    "pituitary tumors",
    "osteoporosis",
    "sexually transmitted infections (STIs)",
    "chlamydia",
    "gonorrhea",
    "syphilis",
    "genital herpes",
    "human papillomavirus (HPV) infection",
    "trichomoniasis",
    "hepatitis B",
    "hepatitis C",
    "HIV/AIDS",
    "genital warts",
    "pelvic inflammatory disease (PID)",
    "prostatitis",
    "epididymitis",
    "orchitis",
    "scabies",
    "lice",
    "pinworms",
    "molluscum contagiosum",
    "scabies",
    "bedbugs",
    "ringworm",
    "athlete's foot",
    "fungal nail infections",
    "yeast infections",
    "thrush",
    "candidiasis",
    "tinea versicolor",
    "eczema",
    "psoriasis",
    "acne",
    "rosacea",
    "hives",
    "contact dermatitis",
    "cellulitis",
    "impetigo",
    "fifth disease",
    "shingles",
    "warts",
    "mumps",
    "measles",
    "rubella",
    "chickenpox",
    "hepatitis A",
    "hepatitis B",
    "hepatitis C",
    "hepatitis D",
    "hepatitis E",
    "influenza",
    "common cold",
    "pneumonia",
    "bronchitis",
    "sinusitis",
    "tuberculosis",
    "strep throat",
    "tonsillitis",
    "pharyngitis",
    "laryngitis",
    "otitis media",
    "conjunctivitis",
    "gastroenteritis",
    "gastritis",
    "gastroesophageal reflux disease (GERD)",
    "peptic ulcer disease",
    "irritable bowel syndrome (IBS)",
    "Crohn's disease",
    "ulcerative colitis",
    "health",
    "wellness",
    "fitness",
    "nutrition",
    "exercise",
    "hygiene",
    "diet",
    "lifestyle",
    "balance",
    "holistic",
    "medication",
    "treatment",
    "therapy",
    "recovery",
    "prevention",
    "vaccination",
    "immunization",
    "screening",
    "diagnosis",
    "symptoms",
    "patient",
    "doctor",
    "nurse",
    "hospital",
    "clinic",
    "pharmacy",
    "medications",
    "prescription",
    "dosage",
    "side effects",
    "adverse reactions",
    "medication adherence",
    "alternative medicine",
    "complementary therapies",
    "integrative health",
    "natural remedies",
    "herbal supplements",
    "holistic healing",
    "mind-body connection",
    "stress management",
    "mental health",
    "anxiety",
    "depression",
    "stress",
    "self-care",
    "self-esteem",
    "self-improvement",
    "self-help",
    "healthy habits",
    "sleep hygiene",
    "smoking cessation",
    "alcohol moderation",
    "substance abuse",
    "addiction recovery",
    "weight management",
    "obesity",
    "cardiovascular health",
    "heart disease",
    "hypertension",
    "diabetes",
    "blood sugar",
    "cholesterol",
    "stroke",
    "cancer",
    "research",
    "clinical trials",
    "genetics",
    "epidemiology",
    "public health",
    "disease prevention",
    "health education",
    "health promotion",
    "community health",
    "global health",
    "infectious diseases",
    "pandemic",
    "epidemic",
    "outbreak",
    "viral",
    "bacterial",
    "fungal",
    "parasitic",
    "respiratory",
    "gastrointestinal",
    "neurological",
    "autoimmune",
    "chronic",
    "acute",
    "inflammation",
    "immune system",
    "vaccines",
    "antibiotics",
    "antiviral",
    "antifungal",
    "antiparasitic",
    "immunodeficiency",
    "immunocompromised",
    "immunosuppression",
    "emerging diseases",
    "zoonotic diseases",
    "vector-borne diseases",
    "pandemic preparedness",
    "disease surveillance",
    "public health policy",
    "healthcare system",
    "telemedicine",
    "health technology",
    "medical devices",
    "data analytics",
    "artificial intelligence",
    "precision medicine",
    "genomic medicine",
    "personalized healthcare",
    "digital health",
    "mobile health",
    "wearable devices",
    "electronic health records",
    "data privacy",
    "medical research",
    "biomedical",
    "pharmaceuticals",
    "drug development",
    "therapeutic advancements",
    "clinical breakthroughs",
    "treatment protocols",
    "disease management",
    "screening guidelines",
    "early detection",
    "genetic testing",
    "prevention strategies",
    "health interventions",
    "community outreach",
    "health disparities",
    "social determinants of health",
    "health equity",
    "healthcare access",
    "health insurance",
    "health literacy",
    "patient empowerment",
    "patient advocacy",
    "patient-centered care",
    "disease eradication",
    "medical breakthroughs",
    "precision medicine",
    "preventive care",
    "primary care",
    "specialty care",
    "hospitalization",
    "rehabilitation",
    "elderly care",
    "pediatric care",
    "women's health",
    "men's health",
    "childhood immunizations",
    "maternal health",
    "reproductive health",
    "sexual health",
    "senior health",
    "aging population",
    "longevity",
    "well-being",
    "health outcomes",
    "quality of life",
    "disability",
    "chronic pain",
    "cognitive health",
    "brain health",
    "neurodegenerative diseases",
    "Alzheimer's disease",
    "Parkinson's disease",
    "multiple sclerosis",
    "cardiovascular diseases",
    "respiratory diseases",
    "asthma",
    "chronic obstructive pulmonary disease",
    "allergies",
    "gastrointestinal diseases",
    "inflammatory bowel disease",
    "liver disease",
    "kidney disease",
    "rheumatoid arthritis",
    "osteoporosis",
    "musculoskeletal disorders",
    "infectious disease outbreaks",
    "tropical diseases",
    "emerging infectious diseases",
    "antimicrobial resistance",
    "public health emergencies",
    "disease control",
    "epidemiological studies",
    "health behavior",
    "disease transmission",
    "epidemiological models",
    "healthcare innovations",
    "biotechnology",
    "nanotechnology",
    "pharmacogenomics",
    "stem cell research",
    "gene therapy",
    "regenerative medicine",
    "drug discovery",
    "clinical research",
    "data science",
    "clinical data analysis",
    "evidence-based medicine",
    "healthcare ethics",
    "healthcare regulations",
    "healthcare economics",
    "healthcare financing",
    "healthcare management",
    "patient safety",
    "medical errors",
    "healthcare disparities",
    "global health initiatives",
    "disease surveillance",
    "health informatics",
    "health technology assessment",
    "digital therapeutics",
    "behavioral health",
    "telehealth",
    "smart healthcare",
    "patient education",
    "health coaching",
    "care coordination",
    "disease prevention programs",
    "health campaigns",
    "community health centers",
    "health screenings",
    "health risk assessment",
    "healthcare workforce",
    "healthcare professionals",
    "medical education",
    "nursing",
    "pharmacy",
    "public health education",
    "health research funding",
    "clinical trials",
    "research ethics",
    "data privacy and security",
    "healthcare innovation ecosystems",
    "collaborative research",
    "translational research",
    "healthcare partnerships",
    "medical breakthroughs",
    "disease eradication",
    "cancer research",
    "heart disease research",
    "diabetes research",
    "mental health research",
    "precision medicine research",
    "health policy development",
    "healthcare reform",
    "public health interventions",
    "prevention programs",
    "health education campaigns",
    "disease awareness",
    "behavioral change",
    "policy implementation",
    "health monitoring",
    "disease tracking",
    "health impact assessment",
    "evidence synthesis",
    "yoga", "youth", "asthma",
    "arthritis",
    "diabetes",
    "cancer",
    "heart disease",
    "Alzheimer's disease",
    "Parkinson's disease",
    "stroke",
    "obesity",
    "depression",
    "anxiety",
    "hypertension",
    "osteoporosis",
    "kidney disease",
    "liver disease",
    "chronic obstructive pulmonary disease (COPD)",
    "multiple sclerosis",
    "autism",
    "schizophrenia",
    "bipolar disorder",
    "attention deficit hyperactivity disorder (ADHD)",
    "migraine",
    "fibromyalgia",
    "endometriosis",
    "polycystic ovary syndrome (PCOS)",
    "Crohn's disease",
    "ulcerative colitis",
    "irritable bowel syndrome (IBS)",
    "hypothyroidism",
    "hyperthyroidism",
    "lupus",
    "rheumatoid arthritis",
    "psoriasis",
    "eczema",
    "malaria",
    "tuberculosis",
    "HIV/AIDS",
    "hepatitis",
    "measles",
    "mumps",
    "rubella",
    "pneumonia",
    "meningitis",
    "bronchitis",
    "gastroenteritis",
    "influenza",
    "cholera",
    "typhoid",
    "syphilis",
    "gonorrhea",
    "chlamydia",
    "herpes",
    "HPV (human papillomavirus)",
    "osteoarthritis",
    "myocardial infarction",
    "asthma",
    "chronic bronchitis",
    "pancreatitis",
    "anemia",
    "leukemia",
    "lymphoma",
    "melanoma",
    "fibroids",
    "endometrial cancer",
    "ovarian cancer",
    "colon cancer",
    "prostate cancer",
    "testicular cancer",
    "breast cancer",
    "lung cancer",
    "pancreatic cancer",
    "bladder cancer",
    "liver cancer",
    "esophageal cancer",
    "stomach cancer",
    "kidney cancer",
    "uterine cancer",
    "bone cancer",
    "skin cancer",
    "thyroid cancer",
    "cervical cancer",
    "ovarian cysts",
    "aneurysm",
    "hemorrhoids",
    "gout",
    "pneumothorax",
    "hemophilia",
    "sickle cell disease",
    "osteoporosis",
    "gastritis",
    "colitis", "asthma",
    "bronchitis",
    "pneumonia",
    "sinusitis",
    "tonsillitis",
    "pharyngitis",
    "conjunctivitis",
    "glaucoma",
    "cataracts",
    "macular degeneration",
    "blindness"
]

filter_words = ["covid"]


def is_relevant(sentence):
    sentence_words = set(word_tokenize(sentence.lower()))
    relevant_words = set()
    for word in words:
        relevant_words.add(word)
        relevant_words |= get_synonyms(word)
    relevant_words -= set(filter_words)
    return bool(sentence_words & relevant_words)


image_terms = [
    "image",
    "picture",
    "photo",
    "photograph",
    "visual",
    "graphic",
    "visualize",
    "visualization",
    "computer vision",
    "image recognition",
    "image classification",
    "3D",
    "3d image"
]


def has_image_relevance(title):
    # Convert the title to lowercase for case-insensitive matching
    title = title.lower()

    # Check if any of the image terms are present in the title
    return any(term in title for term in image_terms)


ear_terms = [
    "ear",
]


def has_ear_relevance(title):
    # Convert the title to lowercase for case-insensitive matching
    title = title.lower()

    # Check if any of the image terms are present in the title
    return any(term in title for term in ear_terms)
